export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"Project home","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"person-chalkboard"},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"Features demo","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"Disabling layout and features","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown Enhance","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"Page Config","i":"file","O":1},[":md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"Guide","i":"lightbulb"},["/guide/README.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","t":"项目主页","i":"home"},["/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar feature","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo feature","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-2b64e284","/zh/demo/",{"y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/zh/demo/README.md"]],
  ["v-c1942916","/zh/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-36295574","/zh/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-47357bdb","/zh/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/zh/guide/README.md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/zh/guide/bar/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-763e2284","/zh/guide/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/zh/guide/foo/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
