server:
  port: 80

spring:
  datasource:
    username: root
    password: qwer54321
    url: jdbc:mysql://sh-cdb-dozq4z36.sql.tencentcdb.com:63865/life?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.springbootbasic.entity
  config: classpath:mybatis-config.xml

logging:
  config:classpath:logback.xml
