
spring:
  profiles:
    # 控制使用哪套环境变量
    active: dev

mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.springbootbasic.entity
  config: classpath:mybatis-config.xml

logging:
  config:classpath:logback.xml
